---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  -  Сайт должен иметь мобильную версию.
  - Сайт нужно протестировать на совместимость с последними версиями браузеров.
  - Важно, чтобы сайт мог обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Сайт должен поддерживать многоязычность для привлечения широкой аудитории.
  - Система должна предоставлять пользователю обратную связь при выполнении действий (например, уведомления о добавлении товара в корзину).
  - Пользователь должен иметь возможность создавать и управлять личным кабинетом, где будет доступна информация о заказах, профиле и настройках.
  - Личный кабинет должен обеспечивать возможность изменения личных данных и управления адресами доставки.
  - Сайт должен работать на всех популярных браузерах и версиях.
  - Функция поиска должна учитывать возможные опечатки и синонимы для улучшения пользовательского опыта.
